### ISSUE TITLE
API route call to FL pickled ZRP model

### ISSUE THREAD

**Issue by dzheng21** [hcs-t4sg/t4sg-zest.ai#19]
create an endpoint in the flask server that can be accessed to retrieve ZRP race predictions. 

afterwards, add documentation for this route (endpoint, route, response bodies, behavior, params, etc. ) to the Github wiki doc for APIs. 

for the params, would imagine that you have name, address, age, and gender. (with the age and gender being subject to change for now). this will likely require a change on the frontend.

**Comment by rnori-harv** [comment]
#30
